/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResqHubRouteImport } from './routes/resq-hub'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as FirstAidRouteImport } from './routes/first-aid'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicVoiceTranscribeRouteImport } from './routes/api.public.voice-transcribe'

const ResqHubRoute = ResqHubRouteImport.update({
  id: '/resq-hub',
  path: '/resq-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAidRoute = FirstAidRouteImport.update({
  id: '/first-aid',
  path: '/first-aid',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceTranscribeRoute =
  ApiPublicVoiceTranscribeRouteImport.update({
    id: '/api/public/voice-transcribe',
    path: '/api/public/voice-transcribe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/first-aid': typeof FirstAidRoute
  '/heroes': typeof HeroesRoute
  '/register': typeof RegisterRoute
  '/resq-hub': typeof ResqHubRoute
  '/api/public/voice-transcribe': typeof ApiPublicVoiceTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/first-aid': typeof FirstAidRoute
  '/heroes': typeof HeroesRoute
  '/register': typeof RegisterRoute
  '/resq-hub': typeof ResqHubRoute
  '/api/public/voice-transcribe': typeof ApiPublicVoiceTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/first-aid': typeof FirstAidRoute
  '/heroes': typeof HeroesRoute
  '/register': typeof RegisterRoute
  '/resq-hub': typeof ResqHubRoute
  '/api/public/voice-transcribe': typeof ApiPublicVoiceTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/first-aid'
    | '/heroes'
    | '/register'
    | '/resq-hub'
    | '/api/public/voice-transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/first-aid'
    | '/heroes'
    | '/register'
    | '/resq-hub'
    | '/api/public/voice-transcribe'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/first-aid'
    | '/heroes'
    | '/register'
    | '/resq-hub'
    | '/api/public/voice-transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  FirstAidRoute: typeof FirstAidRoute
  HeroesRoute: typeof HeroesRoute
  RegisterRoute: typeof RegisterRoute
  ResqHubRoute: typeof ResqHubRoute
  ApiPublicVoiceTranscribeRoute: typeof ApiPublicVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resq-hub': {
      id: '/resq-hub'
      path: '/resq-hub'
      fullPath: '/resq-hub'
      preLoaderRoute: typeof ResqHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-aid': {
      id: '/first-aid'
      path: '/first-aid'
      fullPath: '/first-aid'
      preLoaderRoute: typeof FirstAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-transcribe': {
      id: '/api/public/voice-transcribe'
      path: '/api/public/voice-transcribe'
      fullPath: '/api/public/voice-transcribe'
      preLoaderRoute: typeof ApiPublicVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  FirstAidRoute: FirstAidRoute,
  HeroesRoute: HeroesRoute,
  RegisterRoute: RegisterRoute,
  ResqHubRoute: ResqHubRoute,
  ApiPublicVoiceTranscribeRoute: ApiPublicVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
